### ISSUE TITLE
Reduce too much bandwidth

### ISSUE THREAD

**Issue by F-TD5X** [tohojo/sqm-scripts#60] opened 2017-11-24 12:17 UTC
I am using 100Mbps LAN.
If I start sqm, I can achieve up to 6MB/s download speed.

**Comment by moeller0** [comment] 2017-11-24 12:22
Could you give a bit more information please?
The following would be great:
1) tc -d qdisc
2) tc -s qdisc

if you are using lede/openwrt:
3.a) cat /etc/config/sqm
if on generic linux:
3.b) ls -all /etc/sqm
         then do a cat of your actual configuration file.

**Comment by moeller0** [comment] 2018-10-16 12:04
@F-TD5X is this still an issue, then please supply more information, otherwise I intend to close this issue soon.

**Comment by moeller0** [comment] 2018-10-21 10:34
So due to inactivity and lack of actionable data, I am closing this issue. @F-TD5X please feel free to re-open this or open a new issue, if the issue is not fixed.

**Closed by moeller0** 2018-10-21 10:34 UTC
